### ISSUE TITLE
Why `basic-tests.js` doesn't have `test.js` suffix?

### ISSUE THREAD

**Issue by mikicho** [testjavascript/integration-tests-a-z#18]
@goldbergyoni 
I'm talking about this file: [`example-application/test/basic-tests.js`](https://github.com/testjavascript/integration-tests-a-z/blob/master/example-application/test/basic-tests.js)
By mistake?

**Comment by goldbergyoni** [comment]
Yes and No.

Yes - In real-world project, I'd call this order-api.test.js

No - Here, I wanted to emphasize that it contains examples of basic tests

What is the right name here?

**Comment by mikicho** [comment]
IMO, just add `test` suffix like: `basic-tests.test.js`.

**Comment by goldbergyoni** [comment]
Will do
