### ISSUE TITLE
Rule: disable all http requests to 3rd party services

### ISSUE THREAD

**Issue by mikicho** [testjavascript/integration-tests-a-z#22]
With component test, we thrive to isolate our component from the outside world.
we can do this easily with nock:
```
nock.disableNetConnect();
nock.enableNetConnect('127.0.0.1')
```

**Comment by goldbergyoni** [comment]
✅ Absolutely an important best practice!

Technical challenge - If other collaborators (i.e. other Microservices) are deployed in localhost, then we will allow calls to collaborators which violates the SUT scope. How can we allow calls to the SUT API on localhost but not to collaborators?

**Comment by mikicho** [comment]
from what I see you can enable specific port:
```
nock.enableNetConnect('127.0.0.1:8080')
```

**Comment by goldbergyoni** [comment]
How is this related to docker-compose?

initializeWebServer can easily return the port, shall I add this?

**Comment by mikicho** [comment]
@goldbergyoni each microservice has it's own domain in the network.
