### ISSUE TITLE
Nock enable specific localhost port

### ISSUE THREAD

**Issue by mikicho** [testjavascript/integration-tests-a-z#24]
Do we want to demonstrate how to enable requests to a specific port on localhost with nock?
```
nock.disableNetConnect()
nock.enableNetConnect('127.0.0.1:43050')
```

Maybe this is too `nock` specific and had nothing to do about testing

**Comment by goldbergyoni** [comment]
I would go for this. Here's why?

1. Intercepting requests is at the heart of component tests
2. Isolating components is core best practice
3. Nock is the de-facto interceptor in JS land

**Comment by mikicho** [comment]
@goldbergyoni I think we can close it
