### ISSUE TITLE
DB ram drive work all over including Windows and Mac

### ISSUE THREAD

**Issue by goldbergyoni** [testjavascript/integration-tests-a-z#9]

**Comment by mikicho** [comment]
### Postgres:
Created a benchmark to validate this recommendation.
Unsurprisingly, ram is good :)
The benchmark is a simple 5 select, insert, and update statements,

You can run the benchmark easily:
```
docker run -it --rm -e POSTGRES_PASSWORD=secret postgres:13-alpine sh
docker-entrypoint.sh postgres &
pg_isready -U postgres
pgbench -U postgres -i -s 100
pgbench -U postgres -T 120
```
-----
###  Results:

* **On Disk:**
```
/ # pgbench -U postgres -T 120
starting vacuum...end.
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 100
query mode: simple
number of clients: 1
number of threads: 1
duration: 120 s
number of transactions actually processed: 34755
latency average = 3.453 ms
tps = 289.620594 (including connections establishing)
tps = 289.625784 (excluding connections establishing)
```

* **On Ram:**
(on Windows or Linux, not sure it's working on Mac, I'll check it tomorrow and update)

`docker run -it --rm -e POSTGRES_PASSWORD=secret --tmpfs /var/lib/postgresql/data postgres:13-alpine sh`
```
On Ram:
/ # pgbench -U postgres -T 120
starting vacuum...end.
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 100
query mode: simple
number of clients: 1
number of threads: 1
duration: 120 s
number of transactions actually processed: 101654
latency average = 1.180 ms
tps = 847.112136 (including connections establishing)
tps = 847.125445 (excluding connections establishing)
```
(Maybe even better)

**Comment by mikicho** [comment]
Another interesting thing I learned is there are 2 types of "on-ram" file-systems in Linux `tmpfs` and `ramfs`.
the change that relevant for us is that `tmpfs` may use `swap` so users less likely get OOM exceptions but the performance will be decreased.

**Comment by mikicho** [comment]
@goldbergyoni @jhenaoz @Thormod 
I get an illogical result when running postgres-on-ram-benchmark on mac.

This is what I tried:
1. `diskutil partitionDisk $(hdiutil attach -nomount ram://10240000) 1 GPTFormat APFS 'ramdisk' '100%'`
2. Enable file sharing on `/Volumes/ramdisk` (on docker edge)
3. `docker run -it --rm -e POSTGRES_PASSWORD=secret -v /Volumes/ramdisk/data:/var/lib/postgresql/data postgres:13-alpine sh`

But it slower than running it on disk.
Any of you have experience with this?

**Comment by goldbergyoni** [comment]
These benchmarks are gold, once we go live and show these stats (in nice graphs, even maybe Video), it will greatly help in building trust with the audience. Who doesn't want to get 3x timer faster tests?:)

Core thoughts:
1. Showing these improvements in a typical cloud CI and MAC is really important. There should be our focus. 
2. Let's show this with real tests and docker-compose, as this is the real product. We can create a parameterized test (test.each) with 10K records, including DB insert and get in every test, then run these tests with this in-mem setup. This will show the value over real tests but also allow running this in cloud CI. Note that some CI vendors like CircleCI require to run the docker-compose in machine executors, @Thormod can share an example here or maybe even set the circleci for us. I can create the parameterized test or @mikicho (if you want to train this)

My main point here - This great value should be presented in the environment where 90% of the tests run - CI and Mac

3. About the Mac issue - Let's nail this issue, I just learned about pgbench and my results are consistent with yours 😢. Let's learn more, we may also ask/investigate the Java project testcontainers which is very established one

My results:
pgbench -U postgres -i -s 1
pgbench -U postgres -T 20 -j 3 -c 3

**In-mem**
tps = 1280.949380 (including connections establishing)
tps = 1281.958821 (excluding connections establishing)

**Disc**
tps = 1644.570585 (including connections establishing)
tps = 1644.833938 (excluding connections establishing)

**Comment by mikicho** [comment]
Added [mysql benchmark results](https://github.com/testjavascript/the-art-of-integration-tests/issues/9#issuecomment-710674437).

@goldbergyoni Agree with all your thoughts.
I'll try to investigate the Mac issue further.

**Comment by mikicho** [comment]
It seems like we set the ramdisk appropriately.
What seems weird to me is why ramdisk os "only" 3 times faster than ssd. I thought it will be way faster.

On Disk:
![image](https://user-images.githubusercontent.com/11459632/97079387-21ec2c80-15fc-11eb-931f-80005bbe952e.png)


On Ram:
![image](https://user-images.githubusercontent.com/11459632/97079368-04b75e00-15fc-11eb-8fa0-c44666dc95f8.png)

**Comment by goldbergyoni** [comment]
I'm checking also on Mac. Anyway, 3x times faster sounds sensible given that modern SSD are super-fast. In anyway, I think we have enough to show some solid data, I suggest starting with showing the performance base-line, and then improve upon it. We can show that just-like-this, without advanced optimizations, 100 tests run in 5 seconds (hopefully) which by itself is a great argument and prove that the setup is interesting (e.g. leave the docker-compose up on dev). Practically, I would do the following:

1. Create a folder for performance under 'various-receipes'
2. See the folder ''various-receipes/authentication" which reuses and approaches the main application. It shows how no to copy everything rather just rely on the existing API
3. In your new recipe, Create a JSON with 100 orders data, with copy-paste it should last 1 min
4. Create a parameterized test (test.each), loop over this JSON, approach the API, ensure you get back 200
5. Run 10 times manually, even in watch mode. Maybe the performance is good enough? Run it also over CI, we will have one soon, others might take care of this
6. Try different optimizations, interesting things might come up. For example: tmpfs, run tests in a single process (--runInBand), run in 2,4,8 cores (--maxWorker=), optimize the DB with various flags, ram drive, etc. Yoni can create nice charts based on this

If you want me to do some of these tasks, I'll be glad to help. Thoughts?

**Comment by mikicho** [comment]
I did as you say.
See this [PR summary](https://github.com/testjavascript/integration-tests-a-z/pull/17).

**Comment by goldbergyoni** [comment]
@mikicho I would move the great analysis above (with the numbers) to the performance recipe

**Comment by rluvaton** [comment]
Tested on my mac:
Disk:

![DiskSpeedTest](https://user-images.githubusercontent.com/16746759/212501699-f025f6ca-77b6-4c97-9908-31221ea184b7.png)


RAM:

![DiskSpeedTest](https://user-images.githubusercontent.com/16746759/212501419-b0bd12d7-d4c7-4809-8ab9-3c3568bc9deb.png)

**Comment by mikicho** [comment]
@rluvaton Interesting. please add your mac and OS versions
